// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/transactions/v1/transactions.proto

package transactionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTransactionsByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAddressRequest) Reset() {
	*x = GetTransactionsByAddressRequest{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAddressRequest) ProtoMessage() {}

func (x *GetTransactionsByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionsByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTransactionsByAddressRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsByAddressRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTransactionsByAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*ChirpTransaction    `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByAddressResponse) Reset() {
	*x = GetTransactionsByAddressResponse{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByAddressResponse) ProtoMessage() {}

func (x *GetTransactionsByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByAddressResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsByAddressResponse) GetTransactions() []*ChirpTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsByAddressResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetWeeklyStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyStatisticsRequest) Reset() {
	*x = GetWeeklyStatisticsRequest{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyStatisticsRequest) ProtoMessage() {}

func (x *GetWeeklyStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetWeeklyStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{2}
}

type GetWeeklyStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *TokenStatistics       `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyStatisticsResponse) Reset() {
	*x = GetWeeklyStatisticsResponse{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyStatisticsResponse) ProtoMessage() {}

func (x *GetWeeklyStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetWeeklyStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeeklyStatisticsResponse) GetStatistics() *TokenStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatisticsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetStatisticsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *TokenStatistics       `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatisticsResponse) GetStatistics() *TokenStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type SyncTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTransactionsRequest) Reset() {
	*x = SyncTransactionsRequest{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTransactionsRequest) ProtoMessage() {}

func (x *SyncTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTransactionsRequest.ProtoReflect.Descriptor instead.
func (*SyncTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{6}
}

type SyncTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncTransactionsResponse) Reset() {
	*x = SyncTransactionsResponse{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTransactionsResponse) ProtoMessage() {}

func (x *SyncTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTransactionsResponse.ProtoReflect.Descriptor instead.
func (*SyncTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *SyncTransactionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncTransactionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChirpTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Digest          string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Sender          string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient       string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount          string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionType string                 `protobuf:"bytes,6,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Checkpoint      uint64                 `protobuf:"varint,7,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Success         bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	GasFee          string                 `protobuf:"bytes,10,opt,name=gas_fee,json=gasFee,proto3" json:"gas_fee,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChirpTransaction) Reset() {
	*x = ChirpTransaction{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChirpTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChirpTransaction) ProtoMessage() {}

func (x *ChirpTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChirpTransaction.ProtoReflect.Descriptor instead.
func (*ChirpTransaction) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{8}
}

func (x *ChirpTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChirpTransaction) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ChirpTransaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChirpTransaction) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ChirpTransaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ChirpTransaction) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *ChirpTransaction) GetCheckpoint() uint64 {
	if x != nil {
		return x.Checkpoint
	}
	return 0
}

func (x *ChirpTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChirpTransaction) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChirpTransaction) GetGasFee() string {
	if x != nil {
		return x.GasFee
	}
	return ""
}

type TokenStatistics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalClaimed     string                 `protobuf:"bytes,1,opt,name=total_claimed,json=totalClaimed,proto3" json:"total_claimed,omitempty"`
	TotalTransferred string                 `protobuf:"bytes,2,opt,name=total_transferred,json=totalTransferred,proto3" json:"total_transferred,omitempty"`
	TotalStaked      string                 `protobuf:"bytes,3,opt,name=total_staked,json=totalStaked,proto3" json:"total_staked,omitempty"`
	TotalBought      string                 `protobuf:"bytes,4,opt,name=total_bought,json=totalBought,proto3" json:"total_bought,omitempty"`
	TotalSold        string                 `protobuf:"bytes,5,opt,name=total_sold,json=totalSold,proto3" json:"total_sold,omitempty"`
	UniqueHolders    int64                  `protobuf:"varint,6,opt,name=unique_holders,json=uniqueHolders,proto3" json:"unique_holders,omitempty"`
	TotalTxCount     int64                  `protobuf:"varint,7,opt,name=total_tx_count,json=totalTxCount,proto3" json:"total_tx_count,omitempty"`
	PeriodStart      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenStatistics) Reset() {
	*x = TokenStatistics{}
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenStatistics) ProtoMessage() {}

func (x *TokenStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_api_transactions_v1_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenStatistics.ProtoReflect.Descriptor instead.
func (*TokenStatistics) Descriptor() ([]byte, []int) {
	return file_api_transactions_v1_transactions_proto_rawDescGZIP(), []int{9}
}

func (x *TokenStatistics) GetTotalClaimed() string {
	if x != nil {
		return x.TotalClaimed
	}
	return ""
}

func (x *TokenStatistics) GetTotalTransferred() string {
	if x != nil {
		return x.TotalTransferred
	}
	return ""
}

func (x *TokenStatistics) GetTotalStaked() string {
	if x != nil {
		return x.TotalStaked
	}
	return ""
}

func (x *TokenStatistics) GetTotalBought() string {
	if x != nil {
		return x.TotalBought
	}
	return ""
}

func (x *TokenStatistics) GetTotalSold() string {
	if x != nil {
		return x.TotalSold
	}
	return ""
}

func (x *TokenStatistics) GetUniqueHolders() int64 {
	if x != nil {
		return x.UniqueHolders
	}
	return 0
}

func (x *TokenStatistics) GetTotalTxCount() int64 {
	if x != nil {
		return x.TotalTxCount
	}
	return 0
}

func (x *TokenStatistics) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *TokenStatistics) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

var File_api_transactions_v1_transactions_proto protoreflect.FileDescriptor

const file_api_transactions_v1_transactions_proto_rawDesc = "" +
	"\n" +
	"&api/transactions/v1/transactions.proto\x12\x0ftransactions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n" +
	"\x1fGetTransactionsByAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x7f\n" +
	" GetTransactionsByAddressResponse\x12E\n" +
	"\ftransactions\x18\x01 \x03(\v2!.transactions.v1.ChirpTransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x1c\n" +
	"\x1aGetWeeklyStatisticsRequest\"_\n" +
	"\x1bGetWeeklyStatisticsResponse\x12@\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2 .transactions.v1.TokenStatisticsR\n" +
	"statistics\"\x88\x01\n" +
	"\x14GetStatisticsRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"Y\n" +
	"\x15GetStatisticsResponse\x12@\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2 .transactions.v1.TokenStatisticsR\n" +
	"statistics\"\x19\n" +
	"\x17SyncTransactionsRequest\"N\n" +
	"\x18SyncTransactionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x02\n" +
	"\x10ChirpTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x04 \x01(\tR\trecipient\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12)\n" +
	"\x10transaction_type\x18\x06 \x01(\tR\x0ftransactionType\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\a \x01(\x04R\n" +
	"checkpoint\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12\x17\n" +
	"\agas_fee\x18\n" +
	" \x01(\tR\x06gasFee\"\x8f\x03\n" +
	"\x0fTokenStatistics\x12#\n" +
	"\rtotal_claimed\x18\x01 \x01(\tR\ftotalClaimed\x12+\n" +
	"\x11total_transferred\x18\x02 \x01(\tR\x10totalTransferred\x12!\n" +
	"\ftotal_staked\x18\x03 \x01(\tR\vtotalStaked\x12!\n" +
	"\ftotal_bought\x18\x04 \x01(\tR\vtotalBought\x12\x1d\n" +
	"\n" +
	"total_sold\x18\x05 \x01(\tR\ttotalSold\x12%\n" +
	"\x0eunique_holders\x18\x06 \x01(\x03R\runiqueHolders\x12$\n" +
	"\x0etotal_tx_count\x18\a \x01(\x03R\ftotalTxCount\x12=\n" +
	"\fperiod_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd2\xda\x03\n" +
	"\x13TransactionsService\x12\x81\x01\n" +
	"\x18GetTransactionsByAddress\x120.transactions.v1.GetTransactionsByAddressRequest\x1a1.transactions.v1.GetTransactionsByAddressResponse\"\x00\x12r\n" +
	"\x13GetWeeklyStatistics\x12+.transactions.v1.GetWeeklyStatisticsRequest\x1a,.transactions.v1.GetWeeklyStatisticsResponse\"\x00\x12`\n" +
	"\rGetStatistics\x12%.transactions.v1.GetStatisticsRequest\x1a&.transactions.v1.GetStatisticsResponse\"\x00\x12i\n" +
	"\x10SyncTransactions\x12(.transactions.v1.SyncTransactionsRequest\x1a).transactions.v1.SyncTransactionsResponse\"\x00B\xa5\x01\n" +
	"\x13com.transactions.v1B\x11TransactionsProtoP\x01Z\x1etransactions/v1;transactionsv1\xa2\x02\x03TXX\xaa\x02\x0fTransactions.V1\xca\x02\x0fTransactions\\V1\xe2\x02\x1bTransactions\\V1\\GPBMetadata\xea\x02\x10Transactions::V1b\x06proto3"

var (
	file_api_transactions_v1_transactions_proto_rawDescOnce sync.Once
	file_api_transactions_v1_transactions_proto_rawDescData []byte
)

func file_api_transactions_v1_transactions_proto_rawDescGZIP() []byte {
	file_api_transactions_v1_transactions_proto_rawDescOnce.Do(func() {
		file_api_transactions_v1_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_transactions_v1_transactions_proto_rawDesc), len(file_api_transactions_v1_transactions_proto_rawDesc)))
	})
	return file_api_transactions_v1_transactions_proto_rawDescData
}

var file_api_transactions_v1_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_transactions_v1_transactions_proto_goTypes = []any{
	(*GetTransactionsByAddressRequest)(nil),  // 0: transactions.v1.GetTransactionsByAddressRequest
	(*GetTransactionsByAddressResponse)(nil), // 1: transactions.v1.GetTransactionsByAddressResponse
	(*GetWeeklyStatisticsRequest)(nil),       // 2: transactions.v1.GetWeeklyStatisticsRequest
	(*GetWeeklyStatisticsResponse)(nil),      // 3: transactions.v1.GetWeeklyStatisticsResponse
	(*GetStatisticsRequest)(nil),             // 4: transactions.v1.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),            // 5: transactions.v1.GetStatisticsResponse
	(*SyncTransactionsRequest)(nil),          // 6: transactions.v1.SyncTransactionsRequest
	(*SyncTransactionsResponse)(nil),         // 7: transactions.v1.SyncTransactionsResponse
	(*ChirpTransaction)(nil),                 // 8: transactions.v1.ChirpTransaction
	(*TokenStatistics)(nil),                  // 9: transactions.v1.TokenStatistics
	(*timestamppb.Timestamp)(nil),            // 10: google.protobuf.Timestamp
}
var file_api_transactions_v1_transactions_proto_depIdxs = []int32{
	8,  // 0: transactions.v1.GetTransactionsByAddressResponse.transactions:type_name -> transactions.v1.ChirpTransaction
	9,  // 1: transactions.v1.GetWeeklyStatisticsResponse.statistics:type_name -> transactions.v1.TokenStatistics
	10, // 2: transactions.v1.GetStatisticsRequest.start_time:type_name -> google.protobuf.Timestamp
	10, // 3: transactions.v1.GetStatisticsRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 4: transactions.v1.GetStatisticsResponse.statistics:type_name -> transactions.v1.TokenStatistics
	10, // 5: transactions.v1.ChirpTransaction.timestamp:type_name -> google.protobuf.Timestamp
	10, // 6: transactions.v1.TokenStatistics.period_start:type_name -> google.protobuf.Timestamp
	10, // 7: transactions.v1.TokenStatistics.period_end:type_name -> google.protobuf.Timestamp
	0,  // 8: transactions.v1.TransactionsService.GetTransactionsByAddress:input_type -> transactions.v1.GetTransactionsByAddressRequest
	2,  // 9: transactions.v1.TransactionsService.GetWeeklyStatistics:input_type -> transactions.v1.GetWeeklyStatisticsRequest
	4,  // 10: transactions.v1.TransactionsService.GetStatistics:input_type -> transactions.v1.GetStatisticsRequest
	6,  // 11: transactions.v1.TransactionsService.SyncTransactions:input_type -> transactions.v1.SyncTransactionsRequest
	1,  // 12: transactions.v1.TransactionsService.GetTransactionsByAddress:output_type -> transactions.v1.GetTransactionsByAddressResponse
	3,  // 13: transactions.v1.TransactionsService.GetWeeklyStatistics:output_type -> transactions.v1.GetWeeklyStatisticsResponse
	5,  // 14: transactions.v1.TransactionsService.GetStatistics:output_type -> transactions.v1.GetStatisticsResponse
	7,  // 15: transactions.v1.TransactionsService.SyncTransactions:output_type -> transactions.v1.SyncTransactionsResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_transactions_v1_transactions_proto_init() }
func file_api_transactions_v1_transactions_proto_init() {
	if File_api_transactions_v1_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transactions_v1_transactions_proto_rawDesc), len(file_api_transactions_v1_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_transactions_v1_transactions_proto_goTypes,
		DependencyIndexes: file_api_transactions_v1_transactions_proto_depIdxs,
		MessageInfos:      file_api_transactions_v1_transactions_proto_msgTypes,
	}.Build()
	File_api_transactions_v1_transactions_proto = out.File
	file_api_transactions_v1_transactions_proto_goTypes = nil
	file_api_transactions_v1_transactions_proto_depIdxs = nil
}
