// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/transactions/v1/transactions.proto

package transactionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionsService_GetTransactionsByAddress_FullMethodName = "/transactions.v1.TransactionsService/GetTransactionsByAddress"
	TransactionsService_GetWeeklyStatistics_FullMethodName      = "/transactions.v1.TransactionsService/GetWeeklyStatistics"
	TransactionsService_GetStatistics_FullMethodName            = "/transactions.v1.TransactionsService/GetStatistics"
	TransactionsService_SyncTransactions_FullMethodName         = "/transactions.v1.TransactionsService/SyncTransactions"
)

// TransactionsServiceClient is the client API for TransactionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionsServiceClient interface {
	// GetTransactionsByAddress returns CHIRP token transactions for a specific address
	GetTransactionsByAddress(ctx context.Context, in *GetTransactionsByAddressRequest, opts ...grpc.CallOption) (*GetTransactionsByAddressResponse, error)
	// GetWeeklyStatistics returns token statistics for the last week
	GetWeeklyStatistics(ctx context.Context, in *GetWeeklyStatisticsRequest, opts ...grpc.CallOption) (*GetWeeklyStatisticsResponse, error)
	// GetStatistics returns token statistics for a custom time period
	GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error)
	// SyncTransactions triggers synchronization of transactions from blockchain
	SyncTransactions(ctx context.Context, in *SyncTransactionsRequest, opts ...grpc.CallOption) (*SyncTransactionsResponse, error)
}

type transactionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionsServiceClient(cc grpc.ClientConnInterface) TransactionsServiceClient {
	return &transactionsServiceClient{cc}
}

func (c *transactionsServiceClient) GetTransactionsByAddress(ctx context.Context, in *GetTransactionsByAddressRequest, opts ...grpc.CallOption) (*GetTransactionsByAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsByAddressResponse)
	err := c.cc.Invoke(ctx, TransactionsService_GetTransactionsByAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) GetWeeklyStatistics(ctx context.Context, in *GetWeeklyStatisticsRequest, opts ...grpc.CallOption) (*GetWeeklyStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeeklyStatisticsResponse)
	err := c.cc.Invoke(ctx, TransactionsService_GetWeeklyStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsResponse)
	err := c.cc.Invoke(ctx, TransactionsService_GetStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionsServiceClient) SyncTransactions(ctx context.Context, in *SyncTransactionsRequest, opts ...grpc.CallOption) (*SyncTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncTransactionsResponse)
	err := c.cc.Invoke(ctx, TransactionsService_SyncTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsServiceServer is the server API for TransactionsService service.
// All implementations must embed UnimplementedTransactionsServiceServer
// for forward compatibility.
type TransactionsServiceServer interface {
	// GetTransactionsByAddress returns CHIRP token transactions for a specific address
	GetTransactionsByAddress(context.Context, *GetTransactionsByAddressRequest) (*GetTransactionsByAddressResponse, error)
	// GetWeeklyStatistics returns token statistics for the last week
	GetWeeklyStatistics(context.Context, *GetWeeklyStatisticsRequest) (*GetWeeklyStatisticsResponse, error)
	// GetStatistics returns token statistics for a custom time period
	GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	// SyncTransactions triggers synchronization of transactions from blockchain
	SyncTransactions(context.Context, *SyncTransactionsRequest) (*SyncTransactionsResponse, error)
	mustEmbedUnimplementedTransactionsServiceServer()
}

// UnimplementedTransactionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionsServiceServer struct{}

func (UnimplementedTransactionsServiceServer) GetTransactionsByAddress(context.Context, *GetTransactionsByAddressRequest) (*GetTransactionsByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionsByAddress not implemented")
}
func (UnimplementedTransactionsServiceServer) GetWeeklyStatistics(context.Context, *GetWeeklyStatisticsRequest) (*GetWeeklyStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeeklyStatistics not implemented")
}
func (UnimplementedTransactionsServiceServer) GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedTransactionsServiceServer) SyncTransactions(context.Context, *SyncTransactionsRequest) (*SyncTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncTransactions not implemented")
}
func (UnimplementedTransactionsServiceServer) mustEmbedUnimplementedTransactionsServiceServer() {}
func (UnimplementedTransactionsServiceServer) testEmbeddedByValue()                             {}

// UnsafeTransactionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionsServiceServer will
// result in compilation errors.
type UnsafeTransactionsServiceServer interface {
	mustEmbedUnimplementedTransactionsServiceServer()
}

func RegisterTransactionsServiceServer(s grpc.ServiceRegistrar, srv TransactionsServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionsService_ServiceDesc, srv)
}

func _TransactionsService_GetTransactionsByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).GetTransactionsByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionsService_GetTransactionsByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).GetTransactionsByAddress(ctx, req.(*GetTransactionsByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_GetWeeklyStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).GetWeeklyStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionsService_GetWeeklyStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).GetWeeklyStatistics(ctx, req.(*GetWeeklyStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionsService_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).GetStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionsService_SyncTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsServiceServer).SyncTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionsService_SyncTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsServiceServer).SyncTransactions(ctx, req.(*SyncTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionsService_ServiceDesc is the grpc.ServiceDesc for TransactionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transactions.v1.TransactionsService",
	HandlerType: (*TransactionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTransactionsByAddress",
			Handler:    _TransactionsService_GetTransactionsByAddress_Handler,
		},
		{
			MethodName: "GetWeeklyStatistics",
			Handler:    _TransactionsService_GetWeeklyStatistics_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _TransactionsService_GetStatistics_Handler,
		},
		{
			MethodName: "SyncTransactions",
			Handler:    _TransactionsService_SyncTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/transactions/v1/transactions.proto",
}
